version: "3"

services:
    web:
      image: docker-businessupay-express
      build: ./
      command: node start.js
      ports:
        - "9000:9000"
      volumes: 
        - ./businessupaye-express/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        - "mongo"
    mongo:
      image: "mongo"
      ports:
        - "27017:27017"
    adminmongo: 
      image: "businessupay/adminmongo"
      ports:
        - "1234:1234"







